[package]
name = "dupdir"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
indicatif.workspace = true
investigator.workspace = true
rayon.workspace = true
walkdir.workspace = true
