[workspace]
members = [
    "packages/crates/cli",
    "packages/crates/core",
    "packages/crates/shell",
    "packages/crates/tests",
    "packages/dupdir",
    "packages/find-files-core",
    "packages/find-files-desktop",
    "packages/investigator",
    "packages/utils",
]

[workspace.dependencies]
fastrand = { version = "1.9.0", default-features = false }
find_files_core.path = "packages/crates/core"
find_files_shell.path = "packages/crates/shell"
futures-task = { version = "0.3.28", features = ["alloc"], default-features = false }
hex = { version = "0.4.3", default-features = false }
investigator.path = "packages/investigator"
miniserde = { version = "0.1.34", default-features = false }
model = { version = "0.1.2", default-features = false }
parking_lot = { version = "0.12.1", default-features = false }
pretty_assertions = { version = "1.4.0", features = ["std"], default-features = false }
static_assertions = { version = "1.1.0", default-features = false}
tokio = { version = "1.28.1", default-features = false }
walkdir = { version = "2.4.0", default-features = false }
