[package]
name = "find-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = { version = "2.3.3", default-features = false }
anyhow = { version = "1.0.71", default-features = false, features = ["std"] }
sqlx = { version = "0.6.3", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "migrate", "macros"] }
