[package]
name = "dupdir_core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
dupdir_hash.workspace = true
hex.workspace = true
indicatif.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
