[package]
name = "find_files_shell"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
find_files_core.workspace = true
hex.workspace = true
investigator.workspace = true
static_assertions.workspace = true
walkdir.workspace = true
