[package]
name = "investigator"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[[bin]]
name = "investigator"
test = false

[dependencies]
hex.workspace = true
paste.workspace = true

adler = { optional = true, version = "1.0.2" }
adler32 = { optional = true, version = "1.2.0" }
belt-hash = { optional = true, version = "0.1.0" }
blake2 = { optional = true, version = "0.10.4" }
blake2b_simd = { optional = true, version = "1.0.0" }
blake2s_simd = { optional = true, version = "1.0.0" }
blake3 = { optional = true, version = "1.3.1", features = ["traits-preview"] }
crc32fast = { optional = true, version = "1.3.2" }
digest = { optional = true, version = "0.10.5" }
farmhash = { optional = true, version = "1.1.5" }
fnv = { optional = true, version = "1.0.7" }
fsb = { optional = true, version = "0.1.3" }
fxhash = { optional = true, version = "0.2.1" }
groestl = { optional = true, version = "0.10.1" }
k12 = { optional = true, version = "0.2.1" }
md-5 = { optional = true, version = "0.10.5" }
metrohash = { optional = true, version = "1.0.6" }
ripemd = { optional = true, version = "0.1.3" }
rustc-hash = { optional = true, version = "1.1.0" }
seahash = { optional = true, version = "4.1.0" }
sha2 = { optional = true, version = "0.10.6", features = ["asm"] }
sha3 = { optional = true, version = "0.10.5" }
shabal = { optional = true, version = "0.4.1" }
siphasher = { optional = true, version = "0.3.10" }
sm3 = { optional = true, version = "0.4.1" }
t1ha = { optional = true, version = "0.1.0" }
tiger = { optional = true, version = "0.2.1" }
twox-hash = { optional = true, version = "1.6.3" }
whirlpool = { optional = true, version = "0.10.4" }
#xxhash-rust = { optional = true, version = "0.8.6", features = ["xxh64", "xxh3"] }
xxhash-rust = { optional = true, version = "0.8.6" }
xxhash2 = { optional = true, version = "0.1.0" }

[dev-dependencies]
criterion.workspace = true
rand.workspace = true
tempdir.workspace = true

[[bench]]
name = "benchmark"
harness = false

[features]
default = ["all"]
all = [
    "hash-Adler32",
    "hash-Adler32Rolling",
    "hash-BeltHash",
    "hash-Blake2b",
    "hash-Blake2bSimd",
    "hash-Blake2s",
    "hash-Blake2sSimd",
    "hash-Blake3",
    "hash-Crc32Fast",
    "hash-FarmHash",
    "hash-Fnv",
    "hash-Fsb256",
    "hash-Fsb512",
    "hash-FxHasher",
    "hash-FxHasher32",
    "hash-FxHasher64",
    "hash-FxHasherRustc",
    "hash-Groestl256",
    "hash-Groestl512",
    "hash-KangarooTwelve256",
    "hash-KangarooTwelve512",
    "hash-Md5",
    "hash-MetroHash128",
    "hash-MetroHash64",
    "hash-Ripemd160",
    "hash-Seahash",
    "hash-Sha256",
    "hash-Sha3_256",
    "hash-Sha3_512",
    "hash-Sha512",
    "hash-Shabal512",
    "hash-Siphash",
    "hash-Sm3",
    "hash-T1ha",
    "hash-T1ha2",
    "hash-Tiger",
    "hash-Tiger2",
    "hash-Whirlpool",
    "hash-Xxh2_32",
    "hash-Xxh2_64",
    "hash-Xxh3",
    "hash-Xxh64",
    "hash-Xxh64TwoHash",
]
hash-Adler32 = ["adler"]
hash-Adler32Rolling = ["adler32"]
hash-BeltHash = ["belt-hash"]
hash-Blake2b = ["blake2"]
hash-Blake2bSimd = ["blake2b_simd"]
hash-Blake2s = ["blake2"]
hash-Blake2sSimd = ["blake2s_simd"]
hash-Blake3 = ["digest", "blake3"]
hash-Crc32Fast = ["crc32fast"]
hash-FarmHash = ["farmhash"]
hash-Fnv = ["fnv"]
hash-Fsb256 = ["fsb"]
hash-Fsb512 = ["fsb"]
hash-FxHasher = ["fxhash"]
hash-FxHasher32 = ["fxhash"]
hash-FxHasher64 = ["fxhash"]
hash-FxHasherRustc = ["rustc-hash"]
hash-Groestl256 = ["groestl"]
hash-Groestl512 = ["groestl"]
hash-KangarooTwelve256 = ["digest", "k12"]
hash-KangarooTwelve512 = ["digest", "k12"]
hash-Md5 = ["md-5"]
hash-MetroHash128 = ["metrohash"]
hash-MetroHash64 = ["metrohash"]
hash-Ripemd160 = ["ripemd"]
hash-Seahash = ["seahash"]
hash-Sha256 = ["sha2"]
hash-Sha3_256 = ["sha3"]
hash-Sha3_512 = ["sha3"]
hash-Sha512 = ["sha2"]
hash-Shabal512 = ["shabal"]
hash-Siphash = ["siphasher"]
hash-Sm3 = ["sm3"]
hash-T1ha = ["t1ha"]
hash-T1ha2 = ["t1ha"]
hash-Tiger = ["tiger"]
hash-Tiger2 = ["tiger"]
hash-Whirlpool = ["whirlpool"]
hash-Xxh2_32 = ["xxhash2"]
hash-Xxh2_64 = ["xxhash2"]
hash-Xxh3 = ["xxhash-rust/xxh3"]
hash-Xxh64 = ["xxhash-rust/xxh64"]
hash-Xxh64TwoHash = ["twox-hash"]
