[package]
name = "investigator"
version = "0.1.0"
edition = "2021"

[dependencies]
adler = "1.0.2"
adler32 = "1.2.0"
belt-hash = "0.1.0"
blake2 = "0.10.4"
blake2b_simd = "1.0.0"
blake2s_simd = "1.0.0"
blake3 = { version = "1.3.1", features = ["traits-preview"] }
crc32fast = "1.3.2"
digest = "0.10.5"
farmhash = "1.1.5"
fnv = "1.0.7"
fsb = "0.1.3"
fxhash = "0.2.1"
groestl = "0.10.1"
hex = "0.4.3"
k12 = "0.2.1"
md-5 = { version = "0.10.5" }
metrohash = "1.0.6"
ripemd = "0.1.3"
rustc-hash = "1.1.0"
seahash = "4.1.0"
sha2 = { version = "0.10.6", features = ["asm"] }
sha3 = "0.10.5"
shabal = "0.4.1"
siphasher = "0.3.10"
sm3 = "0.4.1"
t1ha = "0.1.0"
tiger = "0.2.1"
twox-hash = "1.6.3"
whirlpool = "0.10.4"
xxhash-rust = { version = "0.8.6", features = ["xxh64", "xxh3"] }
xxhash2 = "0.1.0"

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"
tempdir = "0.3.7"

[[bench]]
name = "benchmark"
harness = false
